version: "2"

services:
  image:
    build: .
    image: fredrikaverpil/saltstack:1.0
    container_name: salt_image

  master:
    image: fredrikaverpil/saltstack:1.0
    container_name: salt
    hostname: salt
    ports:
      - "4505:4505"
      - "4506:4506"
    volumes:
      - ./assets/master/etc/salt:/etc/salt
      - ./assets/master/var/cache/salt:/var/cache/salt
      - ./assets/master/var/logs/salt:/var/logs/salt
      - ./assets/master/srv/salt:/srv/salt
    command: /usr/bin/salt-master --log-file=/var/logs/salt/salt-master.log --log-file-level=debug

  minion:
    image: fredrikaverpil/saltstack:1.0
    container_name: minion # prevents scaling
    hostname: minion # should be removed if scaling
    ports:
      - "14505:4505"
      - "14506:4506"
    volumes:
      - ./assets/minion/etc/salt:/etc/salt
      - ./assets/minion/var/cache/salt:/var/cache/salt
      - ./assets/minion/var/logs/salt:/var/logs/salt
    command: /usr/bin/salt-minion --log-file=/var/logs/salt/salt-minion.log --log-file-level=debug
